/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OnlineUsersDetails.java
 *
 * Created on 17-feb-2012, 16:36:44
 */
package org.iesapp.modules.userswidget;

import java.awt.Color;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author Josep
 */
public class OnlineUsersSms extends javax.swing.JDialog {
    
    private final int timerInterval = 200;
    private float opacity = 0f;
    private final Timer timer;
    private boolean replay = false;
    private final String abrevRemite;
    private Color[] COLORS;
    private String data;
    private String desde;
    private String sms;
    private boolean enableReply;
    

 
    /** Creates new form OnlineUsersDetails */
    public OnlineUsersSms(java.awt.Frame parent, boolean modal, 
            String desde, String sms, String data, String abrevRemite) {
        super(parent, modal);
        
        COLORS = new Color[]{ new Color(255,255,102), new Color(255,102,255), 
                              new Color(102,255,255), new Color(255,255,225),
                              new Color(255,225,225)};
        //html format
        sms = sms.replaceAll("\n", "<br>");
        
        this.data = data;
        this.desde = desde;
        this.sms = sms;
    
        initComponents();
        
        this.abrevRemite = abrevRemite;
        
        timer = new Timer(timerInterval, new ActionListener ()
        {
                public void actionPerformed(ActionEvent e)
                {
                    opacity += 0.1f;
                    if(opacity>=0.9f) {
                        opacity = 0.9f;
                        timer.stop();
                    } 
                       
                    setOpacity(opacity);
                   
                }

         });
        
        timer.start();
        
        String txt = "<html> "
                + "<body style=\"background-color: rgb("+COLORS[0].getRed()+", "
                +COLORS[0].getGreen()+", "+COLORS[0].getBlue()+"); color: rgb(0, 0, 0);\">"
                + data+"<br> <span style=\"font-weight: bold;\">"+desde +" diu:</span><br>"
                + "<hr style=\"width: 100%; height: 2px;\"><big>"+sms
                +" </big></body>"
                +" </html>";

        
        jTextPane1.setText(txt);
        jTextPane1.setCaretPosition(0);
        
        jButton1.setVisible(this.enableReply);
        
    }

    public void setOpacity(float opac)
    {
         try {
           Class<?> awtUtilitiesClass = Class.forName("com.sun.awt.AWTUtilities");
           Method mSetWindowOpacity = awtUtilitiesClass.getMethod("setWindowOpacity", Window.class, float.class);
           mSetWindowOpacity.invoke(null, this, Float.valueOf(opac));
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(OnlineUsersSms.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(OnlineUsersSms.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OnlineUsersSms.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(OnlineUsersSms.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(OnlineUsersSms.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(OnlineUsersSms.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setBorder(null);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(255, 255, 102));
        jTextPane1.setBorder(null);
        jTextPane1.setContentType("text/html"); // NOI18N
        jTextPane1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextPane1.setName("jTextPane1"); // NOI18N
        jTextPane1.setOpaque(false);
        jScrollPane1.setViewportView(jTextPane1);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("X");
        jLabel2.setToolTipText("Tancar");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/iesapp/modules/userswidget/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("teniuNota")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setText(bundle.getString("constesta")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jButton1))
                .addGap(1, 1, 1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      
        this.dispose();
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setOpacity(opacity);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        propertyChangeSupport.firePropertyChange("replay", "", abrevRemite);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    public boolean isReplay() {
        return replay;
    }
    
    public void setReplay(boolean replay) {
        this.replay=replay;
    }
    
    private PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    public void setPostOrder(int npost) {
       int pos = npost%COLORS.length;
       jPanel1.setBackground(COLORS[pos]);
       String txt = "<html> "
                + "<body style=\"background-color: rgb("+COLORS[pos].getRed()+", "
                +COLORS[pos].getGreen()+", "+COLORS[pos].getBlue()+"); color: rgb(0, 0, 0);\">"
                + data+"<br> <span style=\"font-weight: bold;\">"+desde +" diu:</span><br>"
                + "<hr style=\"width: 100%; height: 2px;\"><big>"+sms
                +" </big></body>"
                +" </html>";

        
        jTextPane1.setText(txt);
        jTextPane1.setCaretPosition(0);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    public void setEnableReply(boolean enableReplay) {
        this.enableReply = enableReplay;
    }

  

 
}
